// Transfert one-shot de l'ancienne base SQLite (hub.db) vers PostgreSQL (pg01).
//
// Prérequis : le schéma cible doit déjà exister (lancer le backend une fois contre
// pg01, initDb crée les tables), et les variables d'environnement doivent pointer :
//   OLD_DB_PATH   chemin du hub.db source (défaut ./data/hub.db)
//   DATABASE_URL  cible postgres://hub:...@192.168.1.54:5432/hub?sslmode=require
//
// Lancement :  OLD_DB_PATH=./data/hub.db DATABASE_URL=... npx tsx scripts/migrate-sqlite-to-pg.ts
//
// Idempotence : chaque table cible est VIDÉE (TRUNCATE) avant réinsertion, donc le
// script peut être relancé sans accumuler de doublons. Les id explicites sont
// réinsérés tels quels (colonnes GENERATED BY DEFAULT AS IDENTITY l'autorisent),
// puis la séquence d'identité est repositionnée sur max(id).

import { createClient } from '@libsql/client'
import { Pool } from 'pg'
import path from 'path'

// Ordre de transfert : un parent avant ses enfants (contraintes FK).
// ean_mappings → catalog ; playlist_items → playlists.
const TABLES = [
  'devices',
  'catalog',
  'ean_mappings',
  'playback_state',
  'playback_history',
  'device_config',
  'credentials',
  'plex_config',
  'lb_games',
  'users',
  'favorites',
  'watched',
  'current_picks',
  'playlists',
  'playlist_items',
  'epg_reminders',
  'iptv_category_prefs',
  'playback_progress',
  'spotify_accounts',
  'trakt_accounts',
  'companion_inbox',
  'llm_providers',
  'llm_settings',
]

// Tables avec colonne id en IDENTITY → séquence à repositionner après transfert.
const IDENTITY_TABLES = [
  'playback_history', 'credentials', 'users', 'favorites', 'watched',
  'current_picks', 'playlists', 'playlist_items', 'epg_reminders',
  'iptv_category_prefs', 'companion_inbox',
]

const OLD_DB_PATH = process.env.OLD_DB_PATH || path.join(process.cwd(), 'data', 'hub.db')
const DATABASE_URL = process.env.DATABASE_URL
if (!DATABASE_URL) {
  console.error('DATABASE_URL manquant (cible Postgres).')
  process.exit(1)
}

const src = createClient({ url: `file:${OLD_DB_PATH}` })
const needSsl = /sslmode=/i.test(DATABASE_URL) || process.env.PGSSL === '1'
const pg = new Pool({
  connectionString: DATABASE_URL.replace(/([?&])sslmode=[^&]*(&|$)/i, '$1').replace(/[?&]+$/, ''),
  ssl: needSsl ? { rejectUnauthorized: false } : undefined,
})

// libsql peut renvoyer des BigInt pour les entiers : on les ramène en number
// (toutes nos valeurs restent < 2^53). Le reste passe tel quel.
function coerce(v: any): any {
  return typeof v === 'bigint' ? Number(v) : v
}

async function tableExists(name: string): Promise<boolean> {
  const r = await src.execute({
    sql: "SELECT name FROM sqlite_master WHERE type='table' AND name = ?",
    args: [name],
  })
  return r.rows.length > 0
}

async function migrateTable(name: string): Promise<number> {
  if (!(await tableExists(name))) {
    console.log(`  - ${name}: absente de la source, ignorée`)
    return 0
  }
  const { rows, columns } = await src.execute(`SELECT * FROM ${name}`)
  await pg.query(`TRUNCATE TABLE ${name} RESTART IDENTITY CASCADE`)
  if (rows.length === 0) {
    console.log(`  - ${name}: 0 ligne`)
    return 0
  }
  const cols = columns as string[]
  const colList = cols.map((c) => `"${c}"`).join(', ')
  const placeholders = cols.map((_, i) => `$${i + 1}`).join(', ')
  const sql = `INSERT INTO ${name} (${colList}) VALUES (${placeholders})`
  const client = await pg.connect()
  try {
    await client.query('BEGIN')
    for (const row of rows as any[]) {
      const values = cols.map((c) => coerce(row[c]))
      await client.query(sql, values)
    }
    await client.query('COMMIT')
  } catch (e) {
    await client.query('ROLLBACK')
    throw e
  } finally {
    client.release()
  }
  console.log(`  - ${name}: ${rows.length} lignes`)
  return rows.length
}

async function resetIdentity(name: string) {
  await pg.query(
    `SELECT setval(pg_get_serial_sequence('${name}', 'id'),
                   GREATEST((SELECT COALESCE(MAX(id), 0) FROM ${name}), 1))`
  )
}

async function main() {
  console.log(`Transfert ${OLD_DB_PATH} → ${DATABASE_URL.replace(/:[^:@/]+@/, ':***@')}`)
  let total = 0
  for (const t of TABLES) total += await migrateTable(t)
  console.log('Repositionnement des séquences d\'identité...')
  for (const t of IDENTITY_TABLES) {
    if (await tableExists(t)) await resetIdentity(t)
  }
  console.log(`Terminé : ${total} lignes transférées au total.`)
  await pg.end()
}

main().catch((e) => {
  console.error('Échec du transfert:', e)
  process.exit(1)
})
