import { Pool, PoolClient, types } from 'pg'
import { hashPin } from './auth'

// ─────────────────────────────────────────────────────────────────────────────
// Adaptateur de compatibilité libsql → PostgreSQL.
// Le reste du code appelle toujours db.execute({sql, args}) / executeMultiple /
// batch / transaction comme avec @libsql/client. Cette couche traduit ces appels
// vers node-postgres : placeholders ? → $1..$n, et un retour {rows, rowsAffected}.
// Objectif : migrer le moteur sans toucher aux ~215 appels répartis dans le code.
// ─────────────────────────────────────────────────────────────────────────────

// pg renvoie les BIGINT (oid 20) en string par défaut (précision JS). Nos colonnes
// de timestamps epoch ms sont en BIGINT : on les reparse en number. Sûr tant que la
// valeur reste < 2^53 (epoch ms ~1.7e12, ids applicatifs bien en dessous).
types.setTypeParser(20, (v) => (v === null ? null : parseInt(v, 10)))

const rawUrl = process.env.DATABASE_URL || 'postgres://hub@192.168.1.54:5432/hub?sslmode=require'

// TLS pg01 = cert self-signed sur le LAN → on chiffre mais sans valider la chaîne.
// On retire sslmode de l'URL : les versions récentes de pg le traitent comme
// verify-full (validation stricte), ce qui écraserait notre rejectUnauthorized:false.
// Le chiffrement reste piloté par l'objet ssl ci-dessous.
const needSsl = /sslmode=/i.test(rawUrl) || process.env.PGSSL === '1'
const connectionString = rawUrl.replace(/([?&])sslmode=[^&]*(&|$)/i, '$1').replace(/[?&]+$/, '')

const pool = new Pool({
  connectionString,
  ssl: needSsl ? { rejectUnauthorized: false } : undefined,
  max: Number(process.env.PG_POOL_MAX || 10),
})

pool.on('error', (err) => {
  console.error('[db] erreur client pg inactif:', err.message)
})

export type Row = Record<string, any>
export interface ExecResult {
  rows: Row[]
  rowsAffected: number
}
export type Stmt = string | { sql: string; args?: any[] }

// Convertit les placeholders positionnels ? (style SQLite) en $1..$n (style pg),
// en sautant le contenu des littéraux entre quotes simples ('' échappé géré).
function toPg(sql: string): string {
  let out = ''
  let n = 0
  let inStr = false
  for (let i = 0; i < sql.length; i++) {
    const c = sql[i]
    if (inStr) {
      out += c
      if (c === "'") {
        if (sql[i + 1] === "'") { out += "'"; i++; continue } // '' = quote échappée
        inStr = false
      }
      continue
    }
    if (c === "'") { inStr = true; out += c; continue }
    if (c === '?') { out += '$' + ++n; continue }
    out += c
  }
  return out
}

function normalize(stmt: Stmt): { text: string; values: any[] } {
  if (typeof stmt === 'string') return { text: toPg(stmt), values: [] }
  // libsql tolère undefined ; pg veut null.
  const values = (stmt.args ?? []).map((v) => (v === undefined ? null : v))
  return { text: toPg(stmt.sql), values }
}

async function run(q: Pool | PoolClient, stmt: Stmt): Promise<ExecResult> {
  const { text, values } = normalize(stmt)
  const r = await q.query(text, values)
  return { rows: r.rows as Row[], rowsAffected: r.rowCount ?? 0 }
}

interface Tx {
  execute(stmt: Stmt): Promise<ExecResult>
  commit(): Promise<void>
  rollback(): Promise<void>
}

export const db = {
  execute(stmt: Stmt): Promise<ExecResult> {
    return run(pool, stmt)
  },

  // Plusieurs statements en une fois (DDL d'init). En protocole simple, pg exécute
  // tout le bloc ; pas de paramètres ici, donc toPg est neutre (aucun ?).
  async executeMultiple(sql: string): Promise<void> {
    await pool.query(toPg(sql))
  },

  // Lot atomique (libsql db.batch(stmts, 'write')) → transaction pg.
  async batch(stmts: Stmt[], _mode?: 'read' | 'write'): Promise<ExecResult[]> {
    const client = await pool.connect()
    try {
      await client.query('BEGIN')
      const out: ExecResult[] = []
      for (const s of stmts) out.push(await run(client, s))
      await client.query('COMMIT')
      return out
    } catch (e) {
      try { await client.query('ROLLBACK') } catch {}
      throw e
    } finally {
      client.release()
    }
  },

  // Transaction explicite (libsql db.transaction('write')) → client dédié du pool.
  async transaction(_mode?: 'read' | 'write'): Promise<Tx> {
    const client = await pool.connect()
    await client.query('BEGIN')
    let done = false
    const finish = async (verb: 'COMMIT' | 'ROLLBACK') => {
      if (done) return
      done = true
      try { await client.query(verb) } finally { client.release() }
    }
    return {
      execute: (stmt: Stmt) => run(client, stmt),
      commit: () => finish('COMMIT'),
      rollback: () => finish('ROLLBACK'),
    }
  },
}

export async function initDb() {
  // Schéma PostgreSQL. AUTOINCREMENT → GENERATED BY DEFAULT AS IDENTITY (permet
  // l'insertion d'id explicites lors du transfert de données). Toutes les colonnes
  // de timestamps epoch ms/s sont en BIGINT (INTEGER pg = int4, max ~2,1e9, trop
  // petit pour un epoch ms ~1,7e12). Les colonnes auparavant ajoutées par ALTER
  // idempotents sont directement intégrées aux CREATE TABLE.
  await db.executeMultiple(`
    CREATE TABLE IF NOT EXISTS devices (
      id TEXT PRIMARY KEY,
      name TEXT NOT NULL,
      platform TEXT NOT NULL,
      ip TEXT,
      last_seen BIGINT NOT NULL,
      capabilities TEXT NOT NULL DEFAULT '[]'
    );

    CREATE TABLE IF NOT EXISTS catalog (
      id TEXT PRIMARY KEY,
      title TEXT NOT NULL,
      type TEXT NOT NULL,
      ean TEXT,
      year INTEGER,
      plex_id TEXT,
      tivimate_id TEXT,
      thumbnail TEXT,
      metadata TEXT NOT NULL DEFAULT '{}'
    );

    CREATE INDEX IF NOT EXISTS idx_catalog_ean ON catalog(ean);
    CREATE INDEX IF NOT EXISTS idx_catalog_title ON catalog(title);

    CREATE TABLE IF NOT EXISTS ean_mappings (
      ean TEXT PRIMARY KEY,
      catalog_id TEXT NOT NULL,
      FOREIGN KEY (catalog_id) REFERENCES catalog(id) ON DELETE CASCADE
    );

    CREATE TABLE IF NOT EXISTS playback_state (
      device_id TEXT PRIMARY KEY,
      catalog_id TEXT,
      app TEXT,
      title TEXT,
      thumb TEXT,
      status TEXT NOT NULL DEFAULT 'stopped',
      started_at BIGINT
    );

    CREATE TABLE IF NOT EXISTS playback_history (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      device_id TEXT NOT NULL,
      catalog_id TEXT,
      app TEXT,
      title TEXT,
      started_at BIGINT NOT NULL,
      ended_at BIGINT,
      requester TEXT NOT NULL DEFAULT 'manual',
      user_id INTEGER
    );

    CREATE TABLE IF NOT EXISTS device_config (
      device_id TEXT PRIMARY KEY,
      xtream_server TEXT NOT NULL DEFAULT '',
      xtream_user TEXT NOT NULL DEFAULT '',
      xtream_pass TEXT NOT NULL DEFAULT '',
      xtream_ext TEXT NOT NULL DEFAULT 'ts',
      plex_server_id TEXT NOT NULL DEFAULT '',
      app_mappings TEXT NOT NULL DEFAULT '{}',
      xtream_credential_id INTEGER,
      tvoverlay_enabled INTEGER NOT NULL DEFAULT 0,
      overlay_player_duration INTEGER NOT NULL DEFAULT 0,
      iptv_player TEXT NOT NULL DEFAULT 'auto',
      updated_at BIGINT NOT NULL DEFAULT 0
    );

    CREATE TABLE IF NOT EXISTS credentials (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      name TEXT NOT NULL,
      type TEXT NOT NULL,
      data TEXT NOT NULL DEFAULT '{}',
      created_at BIGINT NOT NULL DEFAULT 0,
      updated_at BIGINT NOT NULL DEFAULT 0
    );

    CREATE TABLE IF NOT EXISTS plex_config (
      id INTEGER PRIMARY KEY DEFAULT 1,
      client_id TEXT NOT NULL DEFAULT '',
      auth_token TEXT NOT NULL DEFAULT '',
      server_url TEXT NOT NULL DEFAULT '',
      server_machine_id TEXT NOT NULL DEFAULT '',
      updated_at BIGINT NOT NULL DEFAULT 0
    );

    INSERT INTO plex_config (id) VALUES (1) ON CONFLICT (id) DO NOTHING;

    CREATE TABLE IF NOT EXISTS lb_games (
      id TEXT PRIMARY KEY,
      title TEXT NOT NULL,
      platform TEXT NOT NULL DEFAULT '',
      publisher TEXT NOT NULL DEFAULT ''
    );

    CREATE INDEX IF NOT EXISTS idx_lb_games_platform ON lb_games(platform);
    CREATE INDEX IF NOT EXISTS idx_lb_games_title ON lb_games(title);

    CREATE TABLE IF NOT EXISTS users (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      name TEXT NOT NULL,
      avatar_color TEXT NOT NULL DEFAULT '#f59e0b',
      is_admin INTEGER NOT NULL DEFAULT 0,
      pin_hash TEXT,
      created_at BIGINT NOT NULL DEFAULT 0,
      nfc_token TEXT,
      preferred_lang TEXT NOT NULL DEFAULT 'FR',
      default_device_id TEXT,
      default_player TEXT,
      default_playlist_id INTEGER,
      autoplay_next INTEGER NOT NULL DEFAULT 1,
      dashboard_prefs TEXT
    );

    CREATE UNIQUE INDEX IF NOT EXISTS idx_users_nfc ON users(nfc_token) WHERE nfc_token IS NOT NULL;

    CREATE TABLE IF NOT EXISTS favorites (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      user_id INTEGER NOT NULL,
      app TEXT NOT NULL,
      ref_id TEXT NOT NULL,
      ref_type TEXT,
      title TEXT,
      thumb TEXT,
      created_at BIGINT NOT NULL DEFAULT 0,
      UNIQUE(user_id, app, ref_id)
    );

    CREATE INDEX IF NOT EXISTS idx_favorites_user ON favorites(user_id);

    CREATE TABLE IF NOT EXISTS watched (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      user_id INTEGER NOT NULL,
      app TEXT NOT NULL,
      ref_id TEXT NOT NULL,
      ref_type TEXT,
      title TEXT,
      thumb TEXT,
      parent_id TEXT,
      watched_at BIGINT NOT NULL DEFAULT 0,
      UNIQUE(user_id, app, ref_id)
    );

    CREATE INDEX IF NOT EXISTS idx_watched_user ON watched(user_id);

    CREATE TABLE IF NOT EXISTS current_picks (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      user_id INTEGER NOT NULL,
      key TEXT NOT NULL,
      kind TEXT NOT NULL,
      app TEXT,
      ref_id TEXT,
      playlist_id INTEGER,
      title TEXT,
      thumb TEXT,
      created_at BIGINT NOT NULL DEFAULT 0,
      UNIQUE(user_id, key)
    );

    CREATE INDEX IF NOT EXISTS idx_current_user ON current_picks(user_id);

    CREATE TABLE IF NOT EXISTS playlists (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      owner_user_id INTEGER NOT NULL,
      name TEXT NOT NULL,
      description TEXT,
      cover TEXT,
      is_shared INTEGER NOT NULL DEFAULT 0,
      source TEXT NOT NULL DEFAULT 'manual',
      source_url TEXT,
      created_at BIGINT NOT NULL DEFAULT 0,
      updated_at BIGINT NOT NULL DEFAULT 0
    );

    CREATE TABLE IF NOT EXISTS playlist_items (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      playlist_id INTEGER NOT NULL,
      position INTEGER NOT NULL DEFAULT 0,
      app TEXT NOT NULL DEFAULT 'unresolved',
      ref_id TEXT,
      ref_type TEXT,
      title TEXT,
      year INTEGER,
      thumb TEXT,
      lang TEXT,
      status TEXT NOT NULL DEFAULT 'resolved',
      ext TEXT,
      created_at BIGINT NOT NULL DEFAULT 0,
      FOREIGN KEY (playlist_id) REFERENCES playlists(id) ON DELETE CASCADE
    );

    CREATE INDEX IF NOT EXISTS idx_playlist_items_pl ON playlist_items(playlist_id, position);

    CREATE TABLE IF NOT EXISTS epg_reminders (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      user_id INTEGER,
      cred_id INTEGER,
      stream_id TEXT NOT NULL,
      channel_name TEXT,
      title TEXT,
      start_ts BIGINT NOT NULL,
      device_id TEXT,
      lead_min INTEGER NOT NULL DEFAULT 5,
      notified INTEGER NOT NULL DEFAULT 0,
      logo TEXT,
      created_at BIGINT NOT NULL DEFAULT 0
    );

    CREATE INDEX IF NOT EXISTS idx_reminders_due ON epg_reminders(notified, start_ts);

    CREATE TABLE IF NOT EXISTS iptv_category_prefs (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      cred_id INTEGER NOT NULL,
      content_type TEXT NOT NULL,
      category_id TEXT NOT NULL,
      scope TEXT NOT NULL DEFAULT 'global',
      state TEXT NOT NULL CHECK (state IN ('hidden','locked','visible')),
      UNIQUE(cred_id, content_type, category_id, scope)
    );

    CREATE TABLE IF NOT EXISTS playback_progress (
      media_key TEXT PRIMARY KEY,
      catalog_id TEXT,
      app TEXT,
      title TEXT,
      thumb TEXT,
      plex_id TEXT,
      iptv_stream_id TEXT,
      iptv_type TEXT,
      iptv_ext TEXT,
      external_url TEXT,
      external_platform TEXT,
      position BIGINT NOT NULL DEFAULT 0,
      duration BIGINT NOT NULL DEFAULT 0,
      seekable INTEGER NOT NULL DEFAULT 0,
      device_id TEXT,
      user_id INTEGER,
      updated_at BIGINT NOT NULL DEFAULT 0
    );

    CREATE INDEX IF NOT EXISTS idx_progress_updated ON playback_progress(updated_at DESC);

    CREATE TABLE IF NOT EXISTS spotify_accounts (
      user_id INTEGER PRIMARY KEY,
      spotify_user_id TEXT,
      display_name TEXT,
      email TEXT,
      product TEXT,
      access_token TEXT NOT NULL,
      refresh_token TEXT NOT NULL,
      expires_at BIGINT NOT NULL DEFAULT 0,
      scopes TEXT NOT NULL DEFAULT '',
      image TEXT,
      created_at BIGINT NOT NULL DEFAULT 0,
      updated_at BIGINT NOT NULL DEFAULT 0
    );

    CREATE TABLE IF NOT EXISTS trakt_accounts (
      user_id INTEGER PRIMARY KEY,
      trakt_user_id TEXT,
      username TEXT,
      name TEXT,
      access_token TEXT NOT NULL,
      refresh_token TEXT NOT NULL,
      expires_at BIGINT NOT NULL DEFAULT 0,
      scopes TEXT NOT NULL DEFAULT '',
      image TEXT,
      created_at BIGINT NOT NULL DEFAULT 0,
      updated_at BIGINT NOT NULL DEFAULT 0
    );

    CREATE TABLE IF NOT EXISTS companion_inbox (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      user_id INTEGER,
      source_platform TEXT NOT NULL DEFAULT 'tiktok',
      source_url TEXT NOT NULL,
      resolved_url TEXT,
      video_id TEXT,
      caption TEXT,
      author_name TEXT,
      author_unique_id TEXT,
      thumbnail TEXT,
      hashtags TEXT NOT NULL DEFAULT '[]',
      title_guess TEXT,
      year_guess INTEGER,
      type_guess TEXT,
      status TEXT NOT NULL DEFAULT 'pending',
      matched_app TEXT,
      matched_ref_id TEXT,
      matched_title TEXT,
      raw TEXT,
      created_at BIGINT NOT NULL DEFAULT 0,
      updated_at BIGINT NOT NULL DEFAULT 0
    );

    CREATE INDEX IF NOT EXISTS idx_companion_status ON companion_inbox(status, created_at DESC);

    CREATE TABLE IF NOT EXISTS llm_providers (
      provider TEXT PRIMARY KEY,
      api_key TEXT,
      base_url TEXT,
      model TEXT,
      updated_at BIGINT NOT NULL DEFAULT 0
    );

    CREATE TABLE IF NOT EXISTS llm_settings (
      id INTEGER PRIMARY KEY DEFAULT 1,
      active_provider TEXT
    );

    INSERT INTO llm_settings (id) VALUES (1) ON CONFLICT (id) DO NOTHING;

    -- ── Fondation « source de vérité souveraine » (Chantier B) ────────────────
    -- works : l'identité canonique d'une œuvre, possédée par le Hub (id interne),
    -- avec les IDs externes (tmdb/imdb/tvdb) attachés comme attributs copiés une
    -- fois. C'est le point d'ancrage stable des favoris/playlists/progression et,
    -- plus tard, des faits de l'assistant média. norm_key = titre normalisé|année
    -- pour le matching sans ID.
    CREATE TABLE IF NOT EXISTS works (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      type TEXT NOT NULL,
      title TEXT NOT NULL,
      original_title TEXT,
      year INTEGER,
      tmdb_id BIGINT,
      imdb_id TEXT,
      tvdb_id BIGINT,
      norm_key TEXT,
      created_at BIGINT NOT NULL DEFAULT 0,
      updated_at BIGINT NOT NULL DEFAULT 0
    );

    CREATE INDEX IF NOT EXISTS idx_works_tmdb ON works(tmdb_id) WHERE tmdb_id IS NOT NULL;
    CREATE INDEX IF NOT EXISTS idx_works_imdb ON works(imdb_id) WHERE imdb_id IS NOT NULL;
    CREATE INDEX IF NOT EXISTS idx_works_normkey ON works(norm_key);
    CREATE INDEX IF NOT EXISTS idx_works_norm_trgm ON works USING gin (norm_key gin_trgm_ops);

    -- iptv_resolutions : cache de résolution JETABLE. « Où jouer l'œuvre work_id
    -- sur le provider cred_id, dans cette langue, pour cette saison/épisode ».
    -- Recalculable à tout moment ; purgeable en masse au changement de provider
    -- (DELETE WHERE cred_id = ?). season/episode/lang ont des sentinelles non-NULL
    -- (-1 / '') car en SQL deux NULL sont distincts dans une contrainte UNIQUE.
    CREATE TABLE IF NOT EXISTS iptv_resolutions (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      work_id INTEGER NOT NULL,
      cred_id INTEGER NOT NULL,
      kind TEXT NOT NULL,
      season INTEGER NOT NULL DEFAULT -1,
      episode INTEGER NOT NULL DEFAULT -1,
      stream_id TEXT NOT NULL,
      ext TEXT,
      lang TEXT NOT NULL DEFAULT '',
      resolved_at BIGINT NOT NULL DEFAULT 0,
      UNIQUE(work_id, cred_id, kind, season, episode, lang)
    );

    CREATE INDEX IF NOT EXISTS idx_iptvres_work ON iptv_resolutions(work_id, cred_id);
  `)

  // work_id sur les tables qui référencent une œuvre (nullable : migration
  // progressive, items 100 % manuels sans œuvre tolérés). ADD COLUMN IF NOT EXISTS
  // est idempotent en Postgres.
  for (const t of ['playlist_items', 'favorites', 'watched', 'playback_progress']) {
    try { await db.execute(`ALTER TABLE ${t} ADD COLUMN IF NOT EXISTS work_id INTEGER`) } catch {}
  }
  // Saison/épisode sur les items de playlist : nécessaires pour re-résoudre un
  // épisode de série par identité (l'episode_id stocké dans ref_id n'est pas
  // re-dérivable seul après un changement de provider).
  try { await db.execute("ALTER TABLE playlist_items ADD COLUMN IF NOT EXISTS season INTEGER") } catch {}
  try { await db.execute("ALTER TABLE playlist_items ADD COLUMN IF NOT EXISTS episode INTEGER") } catch {}

  // Trace du dernier push vers Trakt (pastille « déjà poussée » + lien vers la liste).
  try { await db.execute("ALTER TABLE playlists ADD COLUMN IF NOT EXISTS trakt_list_url TEXT") } catch {}
  try { await db.execute("ALTER TABLE playlists ADD COLUMN IF NOT EXISTS trakt_pushed_at BIGINT") } catch {}

  // Seed : profil Admin par défaut (PIN 0000) si aucun utilisateur n'existe.
  const { rows: userCount } = await db.execute("SELECT COUNT(*) as n FROM users")
  if (Number((userCount[0] as any).n) === 0) {
    await db.execute({
      sql: "INSERT INTO users (name, avatar_color, is_admin, pin_hash, created_at) VALUES (?, ?, 1, ?, ?)",
      args: ['Admin', '#f59e0b', hashPin('0000'), Date.now()],
    })
    console.log('[db] Profil Admin créé (PIN par défaut: 0000 — à changer dans Admin → Profils)')
  }
}
